"""add phase 4 payment shipping customer analytics tables

Revision ID: 65a1c610afa0
Revises: 0b4385a52a27
Create Date: 2026-03-24 17:16:28.743936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65a1c610afa0'
down_revision: Union[str, Sequence[str], None] = '0b4385a52a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insight',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'snapshot_date', 'type', name='uq_snapshot_farm_date_type')
    )
    op.create_table('customer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('first_order_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_order_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferred_products', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'phone', name='uq_customer_farm_phone')
    )
    op.create_table('payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('toss_payment_key', sa.String(length=200), nullable=True),
    sa.Column('toss_order_id', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('card_company', sa.String(length=50), nullable=True),
    sa.Column('card_number_masked', sa.String(length=20), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('toss_order_id'),
    sa.UniqueConstraint('toss_payment_key')
    )
    op.create_table('shipping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('recipient_name', sa.String(length=100), nullable=False),
    sa.Column('recipient_phone', sa.String(length=20), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('address_detail', sa.String(length=200), nullable=True),
    sa.Column('carrier', sa.String(length=50), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('delivery_message', sa.Text(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipping')
    op.drop_table('payment')
    op.drop_table('customer')
    op.drop_table('analytics_snapshot')
    op.drop_table('ai_insight')
    # ### end Alembic commands ###
